import json

authors_and_books = [
    ("David Foster Wallace", "Infinite Jest"),
    ("Marcus Aurelius", "Meditations"),
    ("Yuval Noah Harari", "Sapiens"),
    ("Niccolò Machiavelli", "The Prince"),
    ("Robert M. Pirsig", "Zen and the Art of Motorcycle Maintenance"),
    ("Jordan B. Peterson", "12 Rules for Life"),
    ("Sun Tzu", "The Art of War"),
    ("Ryan Holiday", "The Obstacle Is the Way"),
    ("Nassim Nicholas Taleb", "Antifragile"),
    ("Nassim Nicholas Taleb", "The Black Swan"),
    ("Ayn Rand", "Atlas Shrugged"),
    ("Ayn Rand", "The Fountainhead"),
    ("Fyodor Dostoevsky", "Crime and Punishment"),
    ("Fyodor Dostoevsky", "Notes from Underground"),
    ("George Orwell", "1984"),
    ("Aldous Huxley", "Brave New World"),
    ("J.D. Salinger", "The Catcher in the Rye"),
    ("F. Scott Fitzgerald", "The Great Gatsby"),
    ("Chuck Palahniuk", "Fight Club"),
    ("Bret Easton Ellis", "American Psycho"),
    ("Jack Kerouac", "On the Road"),
    ("Ernest Hemingway", "The Old Man and the Sea"),
    ("Ernest Hemingway", "A Farewell to Arms"),
    ("Herman Melville", "Moby-Dick"),
    ("Mark Twain", "The Adventures of Huckleberry Finn"),
    ("Friedrich Nietzsche", "Thus Spoke Zarathustra"),
    ("Friedrich Nietzsche", "Beyond Good and Evil"),
    ("Albert Camus", "The Stranger"),
    ("Albert Camus", "The Myth of Sisyphus"),
    ("Jean-Paul Sartre", "Nausea"),
    ("Franz Kafka", "The Metamorphosis"),
    ("Franz Kafka", "The Trial"),
    ("Thomas Pynchon", "Gravity's Rainbow"),
    ("Cormac McCarthy", "Blood Meridian"),
    ("Cormac McCarthy", "The Road"),
    ("J.R.R. Tolkien", "The Lord of the Rings"),
    ("Frank Herbert", "Dune"),
    ("Isaac Asimov", "Foundation"),
    ("Arthur C. Clarke", "2001: A Space Odyssey"),
    ("Philip K. Dick", "Do Androids Dream of Electric Sheep?"),
    ("William Gibson", "Neuromancer"),
    ("Neal Stephenson", "Snow Crash"),
    ("Malcolm Gladwell", "Outliers"),
    ("Malcolm Gladwell", "The Tipping Point"),
    ("Daniel Kahneman", "Thinking, Fast and Slow"),
    ("Ray Dalio", "Principles"),
    ("Walter Isaacson", "Steve Jobs"),
    ("Walter Isaacson", "Elon Musk"),
    ("Ashlee Vance", "Elon Musk"),
    ("Peter Thiel", "Zero to One"),
    ("Ben Horowitz", "The Hard Thing About Hard Things"),
    ("Phil Knight", "Shoe Dog"),
    ("Robert Greene", "The 48 Laws of Power"),
    ("Robert Greene", "Mastery"),
    ("James Clear", "Atomic Habits"),
    ("Mark Manson", "The Subtle Art of Not Giving a F*ck"),
    ("Seneca", "Letters from a Stoic"),
    ("Epictetus", "Enchiridion"),
    ("Homer", "The Iliad"),
    ("Homer", "The Odyssey"),
    ("Plato", "The Republic"),
    ("Aristotle", "Nicomachean Ethics"),
    ("Charles Bukowski", "Post Office"),
    ("Charles Bukowski", "Factotum"),
    ("Hunter S. Thompson", "Fear and Loathing in Las Vegas"),
    ("Tom Wolfe", "The Bonfire of the Vanities"),
    ("Michael Lewis", "Liar's Poker"),
    ("Michael Lewis", "The Big Short"),
    ("John Brooks", "Business Adventures"),
    ("Benjamin Graham", "The Intelligent Investor"),
    ("Burton G. Malkiel", "A Random Walk Down Wall Street"),
    ("Dale Carnegie", "How to Win Friends and Influence People"),
    ("Stephen R. Covey", "The 7 Habits of Highly Effective People"),
    ("Tim Ferriss", "The 4-Hour Workweek"),
    ("David Goggins", "Can't Hurt Me"),
    ("Jocko Willink", "Extreme Ownership"),
    ("Simon Sinek", "Start with Why"),
    ("Cal Newport", "Deep Work"),
    ("Greg McKeown", "Essentialism"),
    ("Viktor E. Frankl", "Man's Search for Meaning"),
    ("Miyamoto Musashi", "The Book of Five Rings"),
    ("Lao Tzu", "Tao Te Ching"),
    ("Carl Jung", "Man and His Symbols"),
    ("Sigmund Freud", "The Interpretation of Dreams"),
    ("Karl Marx", "The Communist Manifesto"),
    ("Adam Smith", "The Wealth of Nations"),
    ("John Stuart Mill", "On Liberty"),
    ("Thomas Hobbes", "Leviathan"),
    ("John Locke", "Two Treatises of Government"),
    ("Jean-Jacques Rousseau", "The Social Contract"),
    ("Ralph Waldo Emerson", "Self-Reliance"),
    ("Henry David Thoreau", "Walden"),
    ("Walt Whitman", "Leaves of Grass"),
    ("Allen Ginsberg", "Howl"),
    ("William S. Burroughs", "Naked Lunch"),
    ("Kurt Vonnegut", "Slaughterhouse-Five"),
    ("Joseph Heller", "Catch-22"),
    ("Don DeLillo", "White Noise"),
    ("Jonathan Franzen", "The Corrections"),
    ("Karl Ove Knausgård", "My Struggle")
]

items = []
for i, (author, title) in enumerate(authors_and_books):
    items.append({
        "brand": author,
        "name": title,
        "mat": "paperback",
        "sale": i % 5 == 0,
        "links": []
    })

data = {"books": items}

with open("data/books.json", "w") as f:
    json.dump(data, f, indent=2)

print("Generated data/books.json with {} items".format(len(items)))
